<?php
echo $this->doctype(); 
?>
<html>
<head>
  <?php echo $this->headTitle()?>
  <?php
     $this->headMeta()->appendHttpEquiv(
            'Content-Type', 
            'text/html; charset=UTF-8'
        );
     echo $this->headMeta() ?>
    <?php echo $this->headScript() ?>
    <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.0/themes/humanity/jquery-ui.css" type="text/css" media="all" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl()?>/css/styles.css" /> 
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.0/jquery-ui.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl()?>/js/points.js"></script>

</head>
<body >
    <?php echo $this->layout()->content ?>
</body>

</html>

